#!/usr/bin/env ruby

require './lib/fpf/config'

def launch(port)
  log_level = ENV.fetch('FPF_PHANTOM_LOG_LEVEL', 'DEBUG')
  log_file = "log/webdriver_#{port}.log"

  cmd =  "phantomjs"
  #BIG FIXME: --webdriver seems to ignore the bind address and just binds to 0.0.0.0,
  #thus in production we're exposing the ports. We SHOULD NOT do that; need to fix this ASAP
  cmd += " --webdriver=127.0.0.1:#{port}"
  cmd += " --webdriver-logfile=#{log_file}" 
  cmd += " --webdriver-loglevel=#{log_level}"
  cmd += " --load-images=false"
  cmd += " --disk-cache=true"
  cmd += " --local-storage-path=tmp/phantom_cache"

  fork do 
    Process.exec(*cmd.split, out: "/dev/null")
  end
end

def shutdown(signal = :QUIT)
  log "FPF Shutting down..."
  $shutdown = true
  $browsers.values.each do |wpid| 
    Process.kill(signal, wpid)
  end
end

def relaunch_children
  find_out_missing_ports.each do |port|
    log "-> relaunching phantomjs for port: #{port.inspect}"
    $browsers[port] = launch(port)
  end
end

def find_out_missing_ports
  $browsers.keys.select do |port|
    not port_open?(port)
  end
end

def port_open?(port)
  system "nc -z localhost #{port} 2>/dev/null 1>/dev/null"
end 

def log(message)
  STDERR.puts message
end

Signal.trap(:INT)  { shutdown(:INT) }
Signal.trap(:QUIT) { shutdown(:QUIT) }
Signal.trap(:TERM) { shutdown(:TERM) }
Signal.trap(:CLD)  { relaunch_children unless $shutdown }

$shutdown = false
$browsers = {}

FullPageFetcher::Config.fetchers_ports.each do |port| 
  if port_open?(port)
    log "ERROR: port #{port} already open; previous Phantom instance open? Aborting"
    shutdown
    break 
  end
  log "Launching phantomjs on port #{port}"
  $browsers[port] = launch(port)
end

Process.waitall

