#!/usr/bin/env bash

set -x

puma \
  --dir "$PWD" \
  --port ${PORT:-4000} \
  --environment ${RACK_ENV:-development} \
  --threads ${CONCURRENCY_MIN:-2}:${CONCURRENCY_MAX:-6} \
  --workers ${CONCURRENCY_WORKERS:-1}

